import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Login from "@/components/Login";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NextAuthProvider from "@/providers/NextAuthProvider";
import ReduxProvider from "@/redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const nexAuthSession = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <NextAuthProvider session={nexAuthSession}>
            <div className="flex flex-col">
              <div className="z-50 w-full fixed ">
                <Navbar />
              </div>
              <div className="absolute z-50 mt-3 right-5">
                <Login />
              </div>
              <div className="z-0 mt-10">{children}</div>
            </div>
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
